/*
 Highmaps JS v5.0.2-modified (2017-03-20)

 (c) 2009-2016 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(n){"object"===typeof module&&module.exports?module.exports=n:n(Highcharts)})(function(n){(function(h){var m=h.each;h.wrap(h.Data.prototype,"init",function(a,k){a.call(this,k);k.svg&&this.loadSVG()});h.extend(h.Data.prototype,{pathToArray:function(a,k){var b=0,e=0,l,q,g=[0,0],f=[0,0],c,d,t=function(a,c){return[c.a*a[0]+c.c*a[1]+c.e,c.b*a[0]+c.d*a[1]+c.f]};a=a.replace(/[0-9]+e-?[0-9]+/g,function(a){return+a}).replace(/([A-Za-z])/g," $1 ").replace(/-/g," -").replace(/^\s*/,"").replace(/\s*$/,
"").replace(/\s+/g," ").split(/[ ,]+/);if(1===a.length)return[];for(b=0;b<a.length;b++)if(l=/[a-zA-Z]/.test(a[b])){d=a[b];q=2;if("c"===d||"C"===d)q=6;"m"===d?f=[parseFloat(a[b+1])+f[0],parseFloat(a[b+2])+f[1]]:"M"===d&&(f=[parseFloat(a[b+1]),parseFloat(a[b+2])]);if("m"===d||"l"===d||"c"===d)a[b]=d.toUpperCase(),c=!0;else if("M"===d||"L"===d||"C"===d)c=!1;else if("h"===d)c=!0,a[b]="L",a.splice(b+2,0,0);else if("v"===d)c=!0,a[b]="L",a.splice(b+1,0,0);else if("s"===d)c=!0,a[b]="L",a.splice(b+1,2);else if("S"===
d)c=!1,a[b]="L",a.splice(b+1,2);else if("H"===d||"h"===d)c=!1,a[b]="L",a.splice(b+2,0,g[1]);else if("V"===d||"v"===d)c=!1,a[b]="L",a.splice(b+1,0,g[0]);else if("z"===d||"Z"===d)g=f}else a[b]=parseFloat(a[b]),c&&(a[b]+=g[e%2]),1===e%2&&k&&(!c||"m"===d&&3>b)&&(l=t([a[b-1],a[b]],k),a[b-1]=l[0],a[b]=l[1]),e===q-1?(g=[a[b-1],a[b]],e=0):e+=1;"number"===typeof a[0]&&4<=a.length&&(a.unshift("M"),a.splice(3,0,"L"));return a},pathToString:function(a){m(a,function(a){var b=a.path,b=b.join(","),b=b.replace(/,?([a-zA-Z]),?/g,
"$1");a.path=b});return a},roundPaths:function(a,k){var b=h.seriesTypes.map.prototype,e,l;e={xAxis:{translate:h.Axis.prototype.translate,options:{},minPixelPadding:0},yAxis:{translate:h.Axis.prototype.translate,options:{},minPixelPadding:0}};b.getBox.call(e,a);l=Math.max(e.maxX-e.minX,e.maxY-e.minY);k=k||1E3;l=k/l;e.xAxis.transA=e.yAxis.transA=l;e.xAxis.len=e.yAxis.len=k;e.xAxis.min=e.minX;e.yAxis.min=(e.minY+k)/l;m(a,function(a){var g,f;a.path=f=b.translatePath.call(e,a.path,!0);for(g=f.length;g--;)"number"===
typeof f[g]&&(f[g]=Math.round(f[g]));delete a._foundBox});return a},loadSVG:function(){function a(a){return Array.prototype.slice.call(a.getElementsByTagName("path")).concat(Array.prototype.slice.call(a.getElementsByTagName("polygon"))).concat(Array.prototype.slice.call(a.getElementsByTagName("rect")))}function k(a){if("path"===a.nodeName)return a.getAttribute("d");if("polygon"===a.nodeName)return a.getAttribute("points");if("rect"===a.nodeName){var b=+a.getAttribute("x"),c=+a.getAttribute("y"),e=
+a.getAttribute("width");a=+a.getAttribute("height");return[b,c,b+e,c,b+e,c+a,b,c+a,b,c].join(" ")}}function b(a){a=a.getCTM();if(!isNaN(a.f))return a}function e(a){var b=a.getElementsByTagName("desc");return(b=b[0]&&b[0].getElementsByTagName("name"))&&b[0]&&b[0].innerText||a.getAttribute("inkscape:label")||a.getAttribute("id")||a.getAttribute("class")}function l(a){return!/fill[\s]?\:[\s]?none/.test(a.getAttribute("style"))&&"none"!==a.getAttribute("fill")}function h(c){var d=[],h,n,p,q,r;g.$frame=
g.$frame||$("\x3cdiv\x3e").css({position:"absolute",top:"-9999em"}).appendTo($(document.body));g.$frame.html(c);c=$("svg",g.$frame)[0];c.removeAttribute("viewBox");n=a(c);m(["defs","clipPath"],function(a){m(c.getElementsByTagName(a),function(a){m(a.getElementsByTagName("path"),function(a){a.skip=!0})})});m(n,function(a,b){if(!a.skip){var c=[];0<b&&a.parentNode!==h&&(r=!0);for(h=a.parentNode;a;)c.push(a),a=a.parentNode;c.reverse();if(p)for(a=0;a<p.length;a++)p[a]!==c[a]&&(p=p.slice(0,a));else p=c}});
q=p[p.length-1];r&&m(q.getElementsByTagName("g"),function(c){var f=[],h;m(a(c),function(a){a.skip||(f=f.concat(g.pathToArray(k(a),b(a))),l(a)&&(h=!0),a.skip=!0)});d.push({name:e(c),path:f,hasFill:h})});m(n,function(a){a.skip||d.push({name:e(a),path:g.pathToArray(k(a),b(a)),hasFill:l(a)})});g.roundPaths(d);f.complete({series:[{data:d}]})}var g=this,f=this.options;-1!==f.svg.indexOf("\x3csvg")?h(f.svg):jQuery.ajax({url:f.svg,dataType:"text",success:h})}})})(n)});